package apps;

import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import models.Helicopter;
import models.Plane;
import models.Platform;
import models.implementations.AirlineImp;
import views.AdminDashboard;
import views.BookingAirline;
import views.CustomerDashboard;
import views.CustomerEditProfil;
import views.Login;
import views.Register;

public class MainFrame extends javax.swing.JFrame {

    private int currentUser;
    private Platform platform;

    public MainFrame() {
        initComponents();
        this.platform = new Platform();
    }

    public int getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(int currentUser) {
        this.currentUser = currentUser;
    }

    public Platform getPlatform() {
        return this.platform;
    }

    private void changeView(JPanel view) {
        this.getContentPane().removeAll();
        this.getContentPane().add(view);
        this.pack();
        this.revalidate();
        this.repaint();
    }

    public void getRegisterView() {
        changeView(new Register(this));
    }

    public void getAdminDashboard() {
        changeView(new AdminDashboard(this));
    }

    public void getCustomerDashboard() {
        changeView(new CustomerDashboard(this));
    }

    public void getCustomerEditProfil() {
        changeView(new CustomerEditProfil(this));
    }

    public void getLoginView() {
        changeView(new Login(this));
    }

    public void getBookingAirline() {
        changeView(new BookingAirline(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wings Nusa Voyage");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(() -> {
            MainFrame mainFrame = new MainFrame();
            AirlineImp airline1 = new Plane("Boeing", "Surabaya", "Blitar", "jsdwhuwhwugryw");
            AirlineImp airline2 = new Plane("Boeing", "Jakarta", "Malang", "advbavdhafdaghdfagdfadghfaghdfad");
            mainFrame.getPlatform().addAirlines(airline1);
            mainFrame.getPlatform().addAirlines(airline2);
            mainFrame.getPlatform().addAirlines(airline2);
            mainFrame.getPlatform().addAirlines(airline2);
            mainFrame.setVisible(true);
            mainFrame.getRegisterView();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
